"""Expected results derived from the statements, not generated by a reference solution.

Each entry is (parameter lines, expected output). Keep these independent when changing code.
"""
CASES = {
    'digit-chain': [(['1'], '0'), (['10'], '1')],
    'locker-hallway': [(['1'], '1 1'), (['100000'], '316 99856')],  # 316² <= 100000 < 317²
    'elevator-trips': [(['10', '10 10'], '2')],
    'spiral-word': [(['A'], 'A'), (['ABCD'], 'ABDC')],
    'roman-addition': [(['IV', 'VI'], 'X')],
    'change-machine': [(['30', '25 10'], 'IMPOSSIBLE')],  # Greedy does not try three tens.
    'stamp-combinations': [(['0', '2 3'], '1'), (['4', '1 2'], '3')],
    'expression-target': [(['0', '00'], '3')],  # All three operators produce zero.
    'maze-routes': [(['#'], '0'), ([';'.join(['.' * 17] * 17)], '601080390')],  # C(32,16)
    'number-safari': [(['00000000'], 'NONE')],
    'knight-moves': [(['a1', 'a1'], '0'), (['a1', 'b3'], '1')],
    'shuffle-cycles': [(['2'], '1'), (['4'], '2')],
    'bowling-night': [([' '.join(['0'] * 20)], '0'), ([' '.join(['10'] * 12)], '300')],
    'hot-potato': [(['1', '5000'], '1'), (['5', '1'], '5')],
    'salvo': [(['A1-A1', 'A1 A1'], 'SM')],
    'chutes-race': [(['1>100', '1'], 'A 1'), (['1>2,2>100', '1'], 'NOBODY 2 0')],
    'yahtzee-roll': [(['6 6 6 6 6'], 'YAHTZEE 50'), (['6 6 6 6 5'], 'FOUROFAKIND 29')],
    'traffic-lights': [(['10/10/5', '1'], '1'), (['15/10/5', '1'], '0')],
    'card-war': [(['7', '7'], 'DRAW 1'), (['14', '2'], 'A 1')],
    'robot-vacuum': [(['R', '1'], '1 E'), (['R', '100000'], '1 N')],
    'mancala-move': [(['0 0 0 0 0 1 0 0 0 0 0 0 0 0', '5'], '0 0 0 0 0 0 1 0 0 0 0 0 0 0 AGAIN')],
    'minesweeper-click': [(['.', '0', '0'], '0'), (['*', '0', '0'], 'BOOM')],
    'rotor-cipher': [(['A', 'ZZZ'], 'A'), (['1 2', 'AAA'], '1 2')],
    'tetris-drop': [(['H8:0'], '0 0 0 0 0 0 0 0'), (['V8:7'], '0 0 0 0 0 0 0 8')],

    # Junior contests 1 and 2, added with the second wave of problems.
    'stair-hops': [(['0'], '1'), (['1'], '1'), (['45'], '1836311903')],  # Fibonacci offset by one
    'digit-persistence': [(['5'], '0'), (['10'], '1')],  # A zero digit collapses in one step.
    'base-parade': [(['1', '2'], '1 1'), (['255', '16'], 'F 2')],
    'bus-route': [(['0:0'], '0 1')],  # An empty route still names stop 1.
    'bracket-depth': [(['('], '-1'), ([')'], '-1'), (['()()'], '1')],
    'skip-counting': [(['6', '6'], '1 0'), (['2', '1'], '2 1')],

    # Junior contests 3 and 4.
    'seat-map': [(['#'], '0 1'), (['..#;#..;###'], '2 1')],  # A tie goes to the earlier row.
    'hot-streak': [(['5'], '1 5'), (['4 4 4'], '1 4')],  # Equal neighbors break a streak.
    'magic-square': [(['5'], '5'), (['1 1;1 1'], '2')],
    'run-length': [(['A'], 'A1'), (['ZZZZZZZZZZZZ'], 'Z12')],  # Two digit run lengths.
    'acronym-maker': [(['a'], 'NONE'), (['abcd'], 'A'), (['abc'], 'NONE')],
    'word-search-row': [(['AAAA', 'AA'], '3'), (['AB', 'ABCDE'], '0')],

    # Senior contests 1 and 2.
    'collatz-peak': [(['1'], '1 0'), (['2'], '2 1')],  # The peak includes the starting value.
    'divisor-champion': [(['1', '1'], '1 1'), (['1', '2'], '2 2')],
    'base-palindrome': [(['0'], '1'), (['9'], '33')],  # Strictly greater, so 9 is not its own answer.
    'postfix-machine': [(['A', 'A=42'], '42'), (['A B +', 'A=1'], 'ERROR')],
    'gray-code': [(['3', '0'], '000'), (['1', '1'], '1')],  # Leading zeros are written out.
    'circulate-cycle': [(['0', '0'], '1 0'), (['1111', '1'], '1 1111')],

    # Senior contests 3 and 4.
    'bst-traversal': [(['+5 -5', 'IN'], 'EMPTY'), (['+5 +5 +5', 'POST'], '5 5 5')],
    'expression-height': [(['A'], '0'), (['((A))'], '0'), (['A+B'], '1')],
    'priority-desk': [(['NEXT'], '-'), (['ADD:a:1'], 'NONE')],
    'shortest-hops': [(['1-2', '1 1'], '0'), (['1-2 3-4', '1 4'], '-1')],
    'gate-network': [(['G1 = BUFFER A'], '1'), (['G1 = NOR A B'], '1')],
    'path-counter': [(['011;101;110', '0 1 2'], '0'), (['0', '0 1 1'], '1')],
}
