"""Expected results derived from the statements, not generated by a reference solution.

Each entry is (parameter lines, expected output). Keep these independent when changing code.
"""
CASES = {
    'digit-chain': [(['1'], '0'), (['10'], '1')],
    'locker-hallway': [(['1'], '1 1'), (['100000'], '316 99856')],  # 316² <= 100000 < 317²
    'elevator-trips': [(['10', '10 10'], '2')],
    'spiral-word': [(['A'], 'A'), (['ABCD'], 'ABDC')],
    'roman-addition': [(['IV', 'VI'], 'X')],
    'change-machine': [(['30', '25 10'], 'IMPOSSIBLE')],  # Greedy does not try three tens.
    'stamp-combinations': [(['0', '2 3'], '1'), (['4', '1 2'], '3')],
    'expression-target': [(['0', '00'], '3')],  # All three operators produce zero.
    'maze-routes': [(['#'], '0'), ([';'.join(['.' * 17] * 17)], '601080390')],  # C(32,16)
    'number-safari': [(['00000000'], 'NONE')],
    'knight-moves': [(['a1', 'a1'], '0'), (['a1', 'b3'], '1')],
    'shuffle-cycles': [(['2'], '1'), (['4'], '2')],
    'bowling-night': [([' '.join(['0'] * 20)], '0'), ([' '.join(['10'] * 12)], '300')],
    'hot-potato': [(['1', '5000'], '1'), (['5', '1'], '5')],
    'salvo': [(['A1-A1', 'A1 A1'], 'SM')],
    'chutes-race': [(['1>100', '1'], 'A 1'), (['1>2,2>100', '1'], 'NOBODY 2 0')],
    'yahtzee-roll': [(['6 6 6 6 6'], 'YAHTZEE 50'), (['6 6 6 6 5'], 'FOUROFAKIND 29')],
    'traffic-lights': [(['10/10/5', '1'], '1'), (['15/10/5', '1'], '0')],
    'card-war': [(['7', '7'], 'DRAW 1'), (['14', '2'], 'A 1')],
    'robot-vacuum': [(['R', '1'], '1 E'), (['R', '100000'], '1 N')],
    'mancala-move': [(['0 0 0 0 0 1 0 0 0 0 0 0 0 0', '5'], '0 0 0 0 0 0 1 0 0 0 0 0 0 0 AGAIN')],
    'minesweeper-click': [(['.', '0', '0'], '0'), (['*', '0', '0'], 'BOOM')],
    'rotor-cipher': [(['A', 'ZZZ'], 'A'), (['1 2', 'AAA'], '1 2')],
    'tetris-drop': [(['H8:0'], '0 0 0 0 0 0 0 0'), (['V8:7'], '0 0 0 0 0 0 0 8')],
}
